export interface AllahName {
  id: number;
  arabic: string;
  transliteration: string;
  meaning: string;
  description: string;
}

export const namesData: AllahName[] = [
  {
    id: 1,
    arabic: "الرَّحْمَنُ",
    transliteration: "Ar-Rahman",
    meaning: "The Most Gracious",
    description: "The One who wills goodness and mercy for all His creatures.",
  },
  {
    id: 2,
    arabic: "الرَّحِيمُ",
    transliteration: "Ar-Raheem",
    meaning: "The Most Merciful",
    description: "The One who acts with extreme kindness.",
  },
  {
    id: 3,
    arabic: "الْمَلِكُ",
    transliteration: "Al-Malik",
    meaning: "The King",
    description: "The Sovereign Lord, The One with absolute Dominion.",
  },
  {
    id: 4,
    arabic: "الْقُدُّوسُ",
    transliteration: "Al-Quddus",
    meaning: "The Most Holy",
    description: "The One who is pure from any imperfection.",
  },
  {
    id: 5,
    arabic: "السَّلاَمُ",
    transliteration: "As-Salam",
    meaning: "The Source of Peace",
    description: "The Giver of peace who is free from every imperfection.",
  },
  {
    id: 6,
    arabic: "الْمُؤْمِنُ",
    transliteration: "Al-Mu'min",
    meaning: "The Guardian of Faith",
    description: "The Giver of belief and the One who fulfills His promises.",
  },
  {
    id: 7,
    arabic: "الْمُهَيْمِنُ",
    transliteration: "Al-Muhaymin",
    meaning: "The Protector",
    description: "The One who witnesses and guards over all things.",
  },
  {
    id: 8,
    arabic: "الْعَزِيزُ",
    transliteration: "Al-Aziz",
    meaning: "The Almighty",
    description: "The Strong, The Defeater who is not defeated.",
  },
  {
    id: 9,
    arabic: "الْجَبَّارُ",
    transliteration: "Al-Jabbar",
    meaning: "The Compeller",
    description: "The Restorer, the One who heals all hearts.",
  },
  {
    id: 10,
    arabic: "الْمُتَكَبِّرُ",
    transliteration: "Al-Mutakabbir",
    meaning: "The Supreme",
    description: "The One who is greater than all creation.",
  },
  {
    id: 11,
    arabic: "الْخَالِقُ",
    transliteration: "Al-Khaliq",
    meaning: "The Creator",
    description:
      "The One who brings everything from non-existence into existence.",
  },
  {
    id: 12,
    arabic: "الْبَارِئُ",
    transliteration: "Al-Bari",
    meaning: "The Originator",
    description: "The One who creates that which is free from any flaws.",
  },
  {
    id: 13,
    arabic: "الْمُصَوِّرُ",
    transliteration: "Al-Musawwir",
    meaning: "The Fashioner",
    description: "The One who gives everything its unique form and shape.",
  },
  {
    id: 14,
    arabic: "الْغَفَّارُ",
    transliteration: "Al-Ghaffar",
    meaning: "The All-Forgiving",
    description: "The One who forgives the sins of His slaves again and again.",
  },
  {
    id: 15,
    arabic: "الْقَهَّارُ",
    transliteration: "Al-Qahhar",
    meaning: "The All-Subduing",
    description: "The One who has power over everything.",
  },
  {
    id: 16,
    arabic: "الْوَهَّابُ",
    transliteration: "Al-Wahhab",
    meaning: "The Bestower",
    description: "The One who gives without measure or expectation of return.",
  },
  {
    id: 17,
    arabic: "الرَّزَّاقُ",
    transliteration: "Ar-Razzaq",
    meaning: "The Provider",
    description: "The One who provides all things beneficial to His creatures.",
  },
  {
    id: 18,
    arabic: "الْفَتَّاحُ",
    transliteration: "Al-Fattah",
    meaning: "The Opener",
    description: "The One who opens the doors of mercy and knowledge.",
  },
  {
    id: 19,
    arabic: "الْعَلِيمُ",
    transliteration: "Al-Alim",
    meaning: "The All-Knowing",
    description: "The One whose knowledge is comprehensive and perfect.",
  },
  {
    id: 20,
    arabic: "الْقَابِضُ",
    transliteration: "Al-Qabid",
    meaning: "The Withholder",
    description: "The One who constricts and restricts.",
  },
  {
    id: 21,
    arabic: "الْبَاسِطُ",
    transliteration: "Al-Basit",
    meaning: "The Extender",
    description: "The One who expands and increases.",
  },
  {
    id: 22,
    arabic: "الْخَافِضُ",
    transliteration: "Al-Khafid",
    meaning: "The Abaser",
    description: "The One who lowers whoever He wills.",
  },
  {
    id: 23,
    arabic: "الرَّافِعُ",
    transliteration: "Ar-Rafi",
    meaning: "The Exalter",
    description: "The One who uplifts whoever He wills.",
  },
  {
    id: 24,
    arabic: "الْمُعِزُّ",
    transliteration: "Al-Mu'izz",
    meaning: "The Giver of Honor",
    description: "The One who grants honor and dignity.",
  },
  {
    id: 25,
    arabic: "الْمُذِلُّ",
    transliteration: "Al-Mudhill",
    meaning: "The Giver of Dishonor",
    description: "The One who humiliates whoever He wills.",
  },
  {
    id: 26,
    arabic: "السَّمِيعُ",
    transliteration: "As-Sami",
    meaning: "The All-Hearing",
    description: "The One who hears everything, open or secret.",
  },
  {
    id: 27,
    arabic: "الْبَصِيرُ",
    transliteration: "Al-Basir",
    meaning: "The All-Seeing",
    description: "The One who sees everything, hidden or manifest.",
  },
  {
    id: 28,
    arabic: "الْحَكَمُ",
    transliteration: "Al-Hakam",
    meaning: "The Judge",
    description: "The Arbitrator whose judgment is final.",
  },
  {
    id: 29,
    arabic: "الْعَدْلُ",
    transliteration: "Al-Adl",
    meaning: "The Just",
    description: "The One who is absolutely equitable.",
  },
  {
    id: 30,
    arabic: "اللَّطِيفُ",
    transliteration: "Al-Latif",
    meaning: "The Subtle One",
    description: "The One who is kind and knows the finest details.",
  },
  {
    id: 31,
    arabic: "الْخَبِيرُ",
    transliteration: "Al-Khabir",
    meaning: "The All-Aware",
    description: "The One who knows the inner truth of everything.",
  },
  {
    id: 32,
    arabic: "الْحَلِيمُ",
    transliteration: "Al-Halim",
    meaning: "The Forbearing",
    description: "The One who does not hasten to punish.",
  },
  {
    id: 33,
    arabic: "الْعَظِيمُ",
    transliteration: "Al-Azim",
    meaning: "The Magnificent",
    description: "The One who is grand beyond measure.",
  },
  {
    id: 34,
    arabic: "الْغَفُورُ",
    transliteration: "Al-Ghafur",
    meaning: "The All-Forgiving",
    description: "The One who forgives sins repeatedly.",
  },
  {
    id: 35,
    arabic: "الشَّكُورُ",
    transliteration: "Ash-Shakur",
    meaning: "The Most Appreciative",
    description: "The One who rewards abundantly for small deeds.",
  },
  {
    id: 36,
    arabic: "الْعَلِيُّ",
    transliteration: "Al-Aliy",
    meaning: "The Most High",
    description: "The One who is high above all.",
  },
  {
    id: 37,
    arabic: "الْكَبِيرُ",
    transliteration: "Al-Kabir",
    meaning: "The Most Great",
    description: "The One who is essentially great.",
  },
  {
    id: 38,
    arabic: "الْحَفِيظُ",
    transliteration: "Al-Hafiz",
    meaning: "The Preserver",
    description: "The One who protects and preserves everything.",
  },
  {
    id: 39,
    arabic: "الْمُقِيتُ",
    transliteration: "Al-Muqit",
    meaning: "The Nourisher",
    description: "The One who gives everyone their sustenance.",
  },
  {
    id: 40,
    arabic: "الْحَسِيبُ",
    transliteration: "Al-Hasib",
    meaning: "The Reckoner",
    description: "The One who suffices for everyone.",
  },
  {
    id: 41,
    arabic: "الْجَلِيلُ",
    transliteration: "Al-Jalil",
    meaning: "The Majestic",
    description: "The One who is sublime and grand.",
  },
  {
    id: 42,
    arabic: "الْكَرِيمُ",
    transliteration: "Al-Karim",
    meaning: "The Most Generous",
    description: "The One who gives without being asked.",
  },
  {
    id: 43,
    arabic: "الرَّقِيبُ",
    transliteration: "Ar-Raqib",
    meaning: "The Watchful",
    description: "The One who observes and records everything.",
  },
  {
    id: 44,
    arabic: "الْمُجِيبُ",
    transliteration: "Al-Mujib",
    meaning: "The Responsive",
    description: "The One who answers every prayer.",
  },
  {
    id: 45,
    arabic: "الْوَاسِعُ",
    transliteration: "Al-Wasi",
    meaning: "The All-Encompassing",
    description: "The One who is vast in knowledge and mercy.",
  },
  {
    id: 46,
    arabic: "الْحَكِيمُ",
    transliteration: "Al-Hakim",
    meaning: "The All-Wise",
    description: "The One who is correct in all His deeds.",
  },
  {
    id: 47,
    arabic: "الْوَدُودُ",
    transliteration: "Al-Wadud",
    meaning: "The Most Loving",
    description: "The One who loves His righteous slaves.",
  },
  {
    id: 48,
    arabic: "الْمَجِيدُ",
    transliteration: "Al-Majid",
    meaning: "The Most Glorious",
    description: "The One who is grand in dignity.",
  },
  {
    id: 49,
    arabic: "الْبَاعِثُ",
    transliteration: "Al-Ba'ith",
    meaning: "The Resurrector",
    description: "The One who brings the dead to life on Judgment Day.",
  },
  {
    id: 50,
    arabic: "الشَّهِيدُ",
    transliteration: "Ash-Shahid",
    meaning: "The Witness",
    description: "The One who is present and sees all things.",
  },
  {
    id: 51,
    arabic: "الْحَقُّ",
    transliteration: "Al-Haqq",
    meaning: "The Absolute Truth",
    description: "The One whose existence is certain and true.",
  },
  {
    id: 52,
    arabic: "الْوَكِيلُ",
    transliteration: "Al-Wakil",
    meaning: "The Trustee",
    description: "The One who can be trusted to handle all affairs.",
  },
  {
    id: 53,
    arabic: "الْقَوِيُّ",
    transliteration: "Al-Qawiyy",
    meaning: "The Most Strong",
    description: "The One who possesses absolute power.",
  },
  {
    id: 54,
    arabic: "الْمَتِينُ",
    transliteration: "Al-Matin",
    meaning: "The Firm One",
    description: "The One whose power is steadfast and unshakeable.",
  },
  {
    id: 55,
    arabic: "الْوَلِيُّ",
    transliteration: "Al-Waliyy",
    meaning: "The Protecting Associate",
    description: "The Friend and Helper of the believers.",
  },
  {
    id: 56,
    arabic: "الْحَمِيدُ",
    transliteration: "Al-Hamid",
    meaning: "The All-Praiseworthy",
    description: "The One who is worthy of all praise.",
  },
  {
    id: 57,
    arabic: "الْمُحْصِي",
    transliteration: "Al-Muhsi",
    meaning: "The Counter",
    description: "The One who knows the count of all things.",
  },
  {
    id: 58,
    arabic: "الْمُبْدِئُ",
    transliteration: "Al-Mubdi",
    meaning: "The Originator",
    description: "The One who begins all creation.",
  },
  {
    id: 59,
    arabic: "الْمُعِيدُ",
    transliteration: "Al-Mu'id",
    meaning: "The Restorer",
    description: "The One who brings back all to life after death.",
  },
  {
    id: 60,
    arabic: "الْمُحْيِي",
    transliteration: "Al-Muhyi",
    meaning: "The Giver of Life",
    description: "The One who grants life to the living.",
  },
  {
    id: 61,
    arabic: "الْمُمِيتُ",
    transliteration: "Al-Mumit",
    meaning: "The Bringer of Death",
    description: "The One who takes away life.",
  },
  {
    id: 62,
    arabic: "الْحَيُّ",
    transliteration: "Al-Hayy",
    meaning: "The Ever-Living",
    description: "The One who is alive and will never die.",
  },
  {
    id: 63,
    arabic: "الْقَيُّومُ",
    transliteration: "Al-Qayyum",
    meaning: "The Self-Sustaining",
    description: "The One who sustains all of existence.",
  },
  {
    id: 64,
    arabic: "الْوَاجِدُ",
    transliteration: "Al-Wajid",
    meaning: "The Perceiver",
    description: "The One who finds whatever He desires.",
  },
  {
    id: 65,
    arabic: "الْمَاجِدُ",
    transliteration: "Al-Majid",
    meaning: "The Illustrious",
    description: "The One who is noble and grand.",
  },
  {
    id: 66,
    arabic: "الْوَاحِدُ",
    transliteration: "Al-Wahid",
    meaning: "The Unique",
    description: "The One who is unique and has no partner.",
  },
  {
    id: 67,
    arabic: "الْأَحَدُ",
    transliteration: "Al-Ahad",
    meaning: "The One",
    description: "The Only One in His essence and attributes.",
  },
  {
    id: 68,
    arabic: "الصَّمَدُ",
    transliteration: "As-Samad",
    meaning: "The Eternal Refuge",
    description: "The One who is sought in every need.",
  },
  {
    id: 69,
    arabic: "الْقَادِرُ",
    transliteration: "Al-Qadir",
    meaning: "The Capable",
    description: "The One who has power over all things.",
  },
  {
    id: 70,
    arabic: "الْمُقْتَدِرُ",
    transliteration: "Al-Muqtadir",
    meaning: "The All-Powerful",
    description: "The One whose power executes all decrees.",
  },
  {
    id: 71,
    arabic: "الْمُقَدِّمُ",
    transliteration: "Al-Muqaddim",
    meaning: "The Expediter",
    description: "The One who brings forward whatever He wills.",
  },
  {
    id: 72,
    arabic: "الْمُؤَخِّرُ",
    transliteration: "Al-Mu'akhkhir",
    meaning: "The Delayer",
    description: "The One who sets back whatever He wills.",
  },
  {
    id: 73,
    arabic: "الْأَوَّلُ",
    transliteration: "Al-Awwal",
    meaning: "The First",
    description: "The One who existed before anything else.",
  },
  {
    id: 74,
    arabic: "الْآخِرُ",
    transliteration: "Al-Akhir",
    meaning: "The Last",
    description: "The One who remains after everything else perishes.",
  },
  {
    id: 75,
    arabic: "الظَّاهِرُ",
    transliteration: "Az-Zahir",
    meaning: "The Manifest",
    description: "The One who is evident and dominant.",
  },
  {
    id: 76,
    arabic: "الْبَاطِنُ",
    transliteration: "Al-Batin",
    meaning: "The Hidden",
    description: "The One who knows the inner state of things.",
  },
  {
    id: 77,
    arabic: "الْوَالِي",
    transliteration: "Al-Wali",
    meaning: "The Governor",
    description: "The One who manages and rules all creation.",
  },
  {
    id: 78,
    arabic: "الْمُتَعَالِي",
    transliteration: "Al-Muta'ali",
    meaning: "The Most Exalted",
    description: "The One who is high above any fault.",
  },
  {
    id: 79,
    arabic: "الْبَرُّ",
    transliteration: "Al-Barr",
    meaning: "The Source of All Goodness",
    description: "The One who is most kind and generous.",
  },
  {
    id: 80,
    arabic: "التَّوَّابُ",
    transliteration: "At-Tawwab",
    meaning: "The Acceptor of Repentance",
    description: "The One who accepts sincere repentance.",
  },
  {
    id: 81,
    arabic: "الْمُنْتَقِمُ",
    transliteration: "Al-Muntaqim",
    meaning: "The Avenger",
    description: "The One who punishes those who persist in rebellion.",
  },
  {
    id: 82,
    arabic: "الْعَفُوُّ",
    transliteration: "Al-Afuww",
    meaning: "The Pardoner",
    description: "The One who erases sins as if they never happened.",
  },
  {
    id: 83,
    arabic: "الرَّؤُوفُ",
    transliteration: "Ar-Ra'uf",
    meaning: "The Compassionate",
    description: "The One who is extremely merciful and kind.",
  },
  {
    id: 84,
    arabic: "مَالِكُ الْمُلْكِ",
    transliteration: "Malik-ul-Mulk",
    meaning: "The Owner of All Sovereignty",
    description: "The Absolute Ruler of all the universe.",
  },
  {
    id: 85,
    arabic: "ذُو الْجَلاَلِ وَالْإِكْرَامِ",
    transliteration: "Dhul-Jalali wal-Ikram",
    meaning: "The Lord of Majesty and Generosity",
    description: "The Owner of grandness and bountifulness.",
  },
  {
    id: 86,
    arabic: "الْمُقْسِطُ",
    transliteration: "Al-Muqsit",
    meaning: "The Equitable",
    description: "The One who acts with absolute justice.",
  },
  {
    id: 87,
    arabic: "الْجَامِعُ",
    transliteration: "Al-Jami",
    meaning: "The Gatherer",
    description: "The One who will gather all on Judgment Day.",
  },
  {
    id: 88,
    arabic: "الْغَنِيُّ",
    transliteration: "Al-Ghaniyy",
    meaning: "The Self-Sufficient",
    description: "The One who is rich and needs nothing.",
  },
  {
    id: 89,
    arabic: "الْمُغْنِي",
    transliteration: "Al-Mughni",
    meaning: "The Enricher",
    description: "The One who gives wealth and sufficiency.",
  },
  {
    id: 90,
    arabic: "الْمَانِعُ",
    transliteration: "Al-Mani",
    meaning: "The Withholder",
    description: "The One who prevents harm or gives as He wills.",
  },
  {
    id: 91,
    arabic: "الضَّارُّ",
    transliteration: "Ad-Darr",
    meaning: "The Distressor",
    description: "The One who can cause harm as a trial or punishment.",
  },
  {
    id: 92,
    arabic: "النَّافِعُ",
    transliteration: "An-Nafi",
    meaning: "The Propitious",
    description: "The One who grants all benefits.",
  },
  {
    id: 93,
    arabic: "النُّورُ",
    transliteration: "An-Nur",
    meaning: "The Light",
    description: "The One who guides and illuminates the heavens and earth.",
  },
  {
    id: 94,
    arabic: "الْهَادِي",
    transliteration: "Al-Hadi",
    meaning: "The Guide",
    description: "The One who shows the straight path.",
  },
  {
    id: 95,
    arabic: "الْبَدِيعُ",
    transliteration: "Al-Badi",
    meaning: "The Incomparable",
    description: "The One who creates in a unique and amazing way.",
  },
  {
    id: 96,
    arabic: "الْبَاقِي",
    transliteration: "Al-Baqi",
    meaning: "The Everlasting",
    description: "The One who will remain forever.",
  },
  {
    id: 97,
    arabic: "الْوَارِثُ",
    transliteration: "Al-Warith",
    meaning: "The Inheritor",
    description: "The One who remains after all creation is gone.",
  },
  {
    id: 98,
    arabic: "الرَّشِيدُ",
    transliteration: "Ar-Rashid",
    meaning: "The Guide to the Right Path",
    description: "The One who acts with perfect wisdom.",
  },
  {
    id: 99,
    arabic: "الصَّبُورُ",
    transliteration: "As-Sabur",
    meaning: "The Patient",
    description: "The One who is most patient and does not hurry.",
  },
];
